import scrapy


class IconsoftCrawlerItem(scrapy.Item):
    filename = scrapy.Field()
    status = scrapy.Field()
    case_number = scrapy.Field()
    disp_date = scrapy.Field()
    disp_stage = scrapy.Field()
    disp_code = scrapy.Field()
    type_of_case = scrapy.Field()
    case_types = scrapy.Field()
    style_of_case = scrapy.Field()
    cause_of_action = scrapy.Field()
    principal_claim = scrapy.Field()
    interest = scrapy.Field()
    interest_other = scrapy.Field()
    attorney_fees = scrapy.Field()
    filing_cost_serve = scrapy.Field()
    fi_fa_fee = scrapy.Field()
    totals = scrapy.Field()
    fi_fa_notes = scrapy.Field()
    types_on_this_case = scrapy.Field()
    cse = scrapy.Field()
    judge = scrapy.Field()
    case_status = scrapy.Field()
    service_date = scrapy.Field()
    answer_date = scrapy.Field()
    projected_default_date = scrapy.Field()
    disposition_date = scrapy.Field()
    stage_of_disposition = scrapy.Field()
    disposition_code = scrapy.Field()
    last_updated_by = scrapy.Field()
    updated_on = scrapy.Field()
    plaintiff = scrapy.Field()
    served_status = scrapy.Field()
    last_name = scrapy.Field()
    first_name = scrapy.Field()
    middle_name = scrapy.Field()
    suffix = scrapy.Field()
    full_name = scrapy.Field()
    unique_case_number = scrapy.Field()
    street = scrapy.Field()
    street2 = scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    zip = scrapy.Field()
    home_phone = scrapy.Field()
    work_phone = scrapy.Field()
    email = scrapy.Field()
    party_type = scrapy.Field()
    service_type = scrapy.Field()

    